name: Hello World

# Trigger workflow on every push
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "🎉 Hello from GitHub Actions! Your workflow is working."
